server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Azhengyijun/springcloud.git #配置git仓库地址
          searchPaths: springcloud #配置仓库路径
          username: Azhengyijun  #访问git仓库的用户名
          password:  Yijun824408065 #访问git仓库的用户密码
      label: master #配置仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/