eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
server:
  port: 8762
spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
      endpoints:
        web:
          exposure:
            include: refresh,health,info

