eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: feign
    #开启熔断器
    feign:
      hystrix:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest